# Generated by Django 5.2.1 on 2025-05-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('location', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_uuid', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('label', models.CharField(choices=[('theft', 'theft'), ('suspicious', 'suspicious'), ('normal', 'normal')], max_length=20)),
                ('time_spotted', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.store')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('api_uid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('api_uid__isnull', False), models.Q(('api_uid__exact', ''), _negated=True)), fields=('api_uid',), name='unique_api_uid_constraint'), models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone__exact', ''), _negated=True)), fields=('phone',), name='unique_phone_constraint')],
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlertSubscripion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_preference', models.CharField(choices=[('standard', 'Standard'), ('critical', 'Critical'), ('both', 'Both')], max_length=20)),
                ('notification_channel', models.CharField(choices=[('api', 'Api')], max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.user')),
            ],
        ),
    ]
